@url = http://localhost:8080

GET {{url}}/tags HTTP/1.1

###
GET {{url}}/tweets/12

###
GET {{url}}/tweets/entity/17
###
GET {{url}}/tweets/15/likes
###

GET {{url}}/tweets/15/replies

###

GET {{url}}/tweets/14/context

###

POST {{url}}/tweets/15/repost HTTP/1.1
Content-Type: application/json

{
  "username": "therealmc",
  "password": "password"
}

###

GET {{url}}/tweets/11/tags

###
GET {{url}}/validate/tag/exists/mario

###

GET {{url}}/validate/username/exists/@therealmc

###

DELETE {{url}}/users/@therealmc HTTP/1.1
Content-Type: application/json

{
  "username": "therealmc",
  "password": "password"
}

###
GET {{url}}/users/@Luigi/tweets HTTP/1.1

###
PATCH {{url}}/users/@therealmc HTTP/1.1
Content-Type: application/json

{
  "username": "therealmc",
  "password": "password"
},
{
  "email": "test@gmail.com",
  "firstName": "testy",
  "lastName": "lastnametest",
  "phone": "1234567"
}
